### ISSUE TITLE
Redmine 2.x Compatible?

### ISSUE THREAD

**Issue by poxtihc** [Loriowar/redmine_issues_tree#1]
Hi! Could you make it 2.x compatible?
It's a great plugin but we use Redmine 2.3 in our company.

Regards

**Comment by Loriowar** [comment]
Hi!
First time I developed this plugin under Redmine 2. You can try to run them under Redmine 2. As I remember, main differences concentrate in "issues/index" template. You can try to implement required hooks in your redefinition of this template and get a profit. This approach is a fastest way to get a working variant.
I think about full support of Redmine 2. It appear in the future. But not in next few days.

**Comment by Loriowar** [comment]
Added support of Redmine 2.6.6. It can be found in the corresponding branch of the plugin. Enjoy.
