### ISSUE TITLE
Link not working when redmine in HTTPS

### ISSUE THREAD

**Issue by amarkstar** [Loriowar/redmine_issues_tree#10]
when redmine in HTTPS but the link still link to HTTP

**Comment by Loriowar** [comment]
Please, try now within plugin from `master` branch. If problem still actual, provide more information about your installation. I haven't any problem with HTTP or HTTPS.

**Comment by amarkstar** [comment]
Thank for reply, below as my installation:

Environment:
  Redmine version                3.0.2.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_agile                  1.3.8
  redmine_ckeditor               1.1.0
  redmine_custom_workflows       0.1.4
  redmine_dashboard              2.5.0
  redmine_email_message_id       0.0.1
  redmine_importer               1.2.2
  redmine_issues_tree            0.0.4
  redmine_screenshot_paste       2.1.0
  redmine_spent_time             3.0.1
  redmine_user_aip_permission    0.0.1
  redmine_wktime                 1.9
  redmine_workflow_hidden_fields 0.2.0


1. in settings pages already setup Protocol = HTTPS
2. When i access project issues pages using HTTPS https://SERVERNAME/projects/PROJECTNAME/issues with a new link "Tree view"
<a class="icon icon-orange-tree issues-tree-view-link" data-link-to-tree-view="/projects/PROJECTNAME/issues_trees/redirect_with_params" href="#">Tree view</a>

3. But when i click the link will redirect to 
http://SERVERNAME/projects/PROJECTNAME/issues_trees/tree_index?c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&c%5B%5D=spent_hours&c%5B%5D=estimated_hours&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=PROJECTNAME&set_filter=1

4. In our production server don't have using port 80 (HTTP), so the client will show server not found.

5. I try debug javascript, in tree.helper.js line 15 window.location.href = data.redirect; the data.redirect is return URL without HTTPS.

6. Is it redirect URL is return from issues_trees_controller.rb? 
Sorry i'm not very well for ruby. so i only can debug up to here.

**Comment by Loriowar** [comment]
Yesterday before writing the comment I made a commit with bugfix into the `master`. This bugfix change behaviour of "Tree view" link and in `data.redirect` now must appear link without domain name. So, now there must be relative url like `/projects/name/issue_tree_view/` instead of `http://myDomain:port/projects/name/issue_tree_view/` in old case. If you pull changes from `master` and still see an error - this is very interestring problem.

**Comment by amarkstar** [comment]
I try manually update issues_trees_controller.rb based on master branch, is working now. maybe have some error i mistaken when i pull changes. anyway, thank a lot.

**Comment by Loriowar** [comment]
You are welcome. I will merge this changes in all supported branches within next few days.
