### ISSUE TITLE
Connection is not possible in the tree view.

### ISSUE THREAD

**Issue by yakkung** [Loriowar/redmine_issues_tree#100]
In the case of a tree display, the following logs are continuously output to production.log.

   Rendered plugins / redmine_issues_tree / apps / views / issues_trees / _tree_node.html.erb (XX.Xms)

I'm having trouble connecting because of a proxy error.
Remote connection to the server is also not possible.
If it is set to normal display, log will not be output and connection will be made normally.
Are there any countermeasures?
Sorry for my weird English.

**Comment by Loriowar** [comment]
Hi. Can't understand the relation of proxy problem and with current plugin. There is no explicit log calls in the plugin. Moreover, I can't understand how plugin can affect on network layer. So, if possible, please, provide more details about Redmine configuration and about proxy problem with its configuratuni and logs.

**Comment by yakkung** [comment]
Thank you for your answer.
Unless the plugin is writing logs, I think there is no problem with the plug-in.
The root cause is probably the number of tickets (around 4000).
I am sorry that I cannot provide specific information because it is related to customer service.
Thank you very much.

**Comment by Loriowar** [comment]
Yea, lots of issues within a single node is a problem. There is no pagination in the plugin in the tree view. So, it can be slow, or raise an error due to lots of resources consumption and/or long network response. Details about pagination can be found in https://github.com/Loriowar/redmine_issues_tree/issues/3#issuecomment-139799782

**Comment by shaphiro** [comment]
> Yea, lots of issues within a single node is a problem. There is no pagination in the plugin in the tree view. So, it can be slow, or raise an error due to lots of resources consumption and/or long network response. Details about pagination can be found in [#3 (comment)](https://github.com/Loriowar/redmine_issues_tree/issues/3#issuecomment-139799782)

Regarding pagination is there any intention to develop an optimized version of this plugin? Thanks

**Comment by Loriowar** [comment]
@shaphiro this is a good question. First of all, as you might see, there are multiple way to implement such "optimized" version. So, no way to do a single solution for all possible use cases. That is why that task is not in priority. But, you're welcome to write a solution for your partocular case. Then, I can help with integration of it into the plugin.
