### ISSUE TITLE
Cannot run in 4.1.0 redmine.

### ISSUE THREAD

**Issue by CNPF** [Loriowar/redmine_issues_tree#102]
with redmine 4.1.0 stable encount following problem. I use branch 4.0.* 

`App 19984 stderr: NoMethodError (undefined method `permit' for #<ActiveSupport::HashWithIndifferentAccess:0x00563a02f35c68>
App 19984 stderr: Did you mean?  print):
App 19984 stderr:
App 19984 stderr: plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:8:in `index'
App 19984 stderr: lib/redmine/sudo_mode.rb:65:in `sudo_mode'`

thanks

**Comment by Loriowar** [comment]
@CNPF fixed, please, switch to `4.1.x` branch and check working of the plugin.

**Comment by CNPF** [comment]
@Loriowar no problem of 4.1.* branch..
Thank you so much
