### ISSUE TITLE
Language fr.yml

### ISSUE THREAD

**Issue by CNPF** [Loriowar/redmine_issues_tree#103]
French translation is here attached. Nothing more to say, I think ;)
fr.yml.txt
[fr.yml.txt](https://github.com/Loriowar/redmine_issues_tree/files/4029917/fr.yml.txt)

**Comment by Loriowar** [comment]
@CNPF thanks for localization. Added to all supported versions.

Moreover, added smal fixes of plugin according to Redmine 4.1 changes. Please, pull it from corresponding branch.
