### ISSUE TITLE
16f72102 needed for 4.0.x

### ISSUE THREAD

**Issue by frnky** [Loriowar/redmine_issues_tree#104]
I encountered the following problem with the redmine 4.0.x branch of redmine_issues_tree and redmine 4.0.6:

Processing by IssuesController#index as HTML
  Parameters: {"set_filter"=>"1", "tracker_id"=>"1", "project_id"=>"a-test"}
  Current user: anonymous
Completed 500 Internal Server Error in 98ms (ActiveRecord: 21.0ms)
  
NoMethodError (undefined method `permit' for #<ActiveSupport::HashWithIndifferentAccess:0x000055d33891cd58>):
  
plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:8:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Versions used:
 Redmine version  4.0.6.stable
 Ruby version  2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
 Rails version 5.2.4.1
redmine_issues_tree, branch 4.0.x, commit 88bb912

The error was gone after applying 16f72102 from the 4.1.x branch.

**Comment by Loriowar** [comment]
@frnky try to use branch `4.1.x`. There was changes with fixing of similar issue (#102). I'll look at current issue with 4.0.6 version little later.

**Comment by frnky** [comment]
Thanks! Yes, the branch 4.1.x works for me with redmine 4.0.6.

**Comment by AleksanderKruecken** [comment]
I have Redmine 4.0.4.

When I installed the plugin branch for 4.0.x I got the following error when clicking on the tab 'Issues':

```
Started GET "/projects/11-022-cng-vrem-post-semart-mp-ii/issues" for 84.255.242.180 at 2020-01-10 13:41:46 +0100
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"11-022-cng-vrem-post-semart-mp-ii"}
  Current user: alex (id=2)
Completed 500 Internal Server Error in 17ms (ActiveRecord: 4.6ms)

NoMethodError (undefined method `permit' for #<Hash:0x0000000960e1a0>
Did you mean?  print):
```
I have then removed 4.0.x branch and instaled 4.1.x branch as recomended. Then the whole Redmine stopped working.

**Comment by AleksanderKruecken** [comment]
Sorry, I downloaded master instead of branch 4.1.x.

**Comment by AleksanderKruecken** [comment]
I have now insaled branch 4.1.x on 4.0.4.
When I go to plugins tab in Redmine GUI and press Configure for this plugin, I get HTTP 404 error

GET https://redmine.artes.si/settings/plugin/redmine_issues_tree

Answer:
404 Not Found

**Comment by Loriowar** [comment]
@AleksanderKruecken I can't reproduce 404 error on the plugin settings. For clear Redine `4.0.4` and  for`4.0-stable` the settings page and the tree view working correct in case of `4.1.x` branch of this plugin.

**Comment by AleksanderKruecken** [comment]
Got it working. I had to remove version from the folder name. Thanks
