### ISSUE TITLE
Please consider renaming the master branch

### ISSUE THREAD

**Issue by Soundbytes** [Loriowar/redmine_issues_tree#106]
Hi,

following the desaster with my own pull request I went through the issues and pull requests. I found that quite a number had been opened in error because people made the same mistake as I and had checked out the master branch.
Many users expect to find the lastest stable version in master because it is a widely followed convention among developers to organize repositories that way.  
So may I ask that you rename the master branch to dev or something alike and use master for what is currently 4.1?
I really love your plugin and frankly the issues page in redmine does not make any sense to me without it. So I spent an entire day learning ruby and fixing the problem only to find out that I had just been reinventing the wheel. (And I am in good company given the pull request history.)
Thanks for listening
Andreas Sumerauer

**Comment by Loriowar** [comment]
Hi!

I dropped all functions from `master` branch and leave only plugin initialization and explicit notification about way of plugin installation.

Leave the latest supported version in the `master` is not a best idea because plugin overwrites `issues#index` template which changing in each Redmine release. Moreover, there can be incompatible patches of helpers/controllers/etc. And finally, not all people use plugin with the latest Redmine version. So, no guarantee of proper plugin works in case of `master` branch. That is why I asking all users to download the proper branch.

**Comment by konpega** [comment]
Hello gentlemen
I am a new user for redmine. I am using on windows redmine plus agile 4.1.0-8. I tried to install two times with the folder name.
But redmine collapsed. What do you  mean with the master? How can we install this plugin?
I appreciate if you explain it a little bit detailed . Thanks in advance.

![folder1](https://user-images.githubusercontent.com/61666724/79968110-5be74500-8498-11ea-9789-4feef70cccb4.png)
![folder2](https://user-images.githubusercontent.com/61666724/79968116-5d187200-8498-11ea-9716-6c466472c16b.png)

**Comment by Loriowar** [comment]
@konpega preferable, to create a selarate issue for your problem. Most likely, my plugin not compatible with some of other installed in your Redmine. So, you can adjust this and create a PR or consider to not use one of conflected plugins.

Regadding `master` branch: use branch with name, corresppnding to your Redmine version. For example, here is branch for [4.1.x Redmine](https://github.com/Loriowar/redmine_issues_tree/tree/4.1.x).

**Comment by konpega** [comment]
Sorry if I did something wrong. I thought that the problem somehow is related with the branch. Thanks for the branch link.

**Comment by Soundbytes** [comment]
@konpega Thanks for the clarification an d for slimming down the master branch. This will hopefully save some folks from trying to use it.
