### ISSUE TITLE
Can't install in redmine 4.1.x (4.1.0)

### ISSUE THREAD

**Issue by pcpostar** [Loriowar/redmine_issues_tree#107]
I tried installing:
1. clone from git
2. run command
```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for IssuesController:Class
Did you mean?  alias_method
```

```
[root@redmine redmine]# rails --version
Rails 5.2.4.1
[root@redmine redmine]# ruby --version
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
[root@redmine redmine]# rake --version
rake, version 13.0.1
```
Am I doing anything wrong here?

**Comment by Loriowar** [comment]
Look like you use `master` branch of the plugin instead of branch with the name corresponding to your Redmine version. Try to use branch `4.1.x`.

**Comment by pcpostar** [comment]
Thank you. Solved.

Had to chose the right branch, correct. Thank you!
In folder plugins issue command:
`git clone --single-branch --branch "4.1.x" https://github.com/Loriowar/redmine_issues_tree.git
`

Thank you!
