### ISSUE TITLE
not working 4.0.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [Loriowar/redmine_issues_tree#108]
Completed 500 Internal Server Error in 42ms (ActiveRecord: 12.2ms)
  
NoMethodError (undefined method `permit' for #<ActiveSupport::HashWithIndifferentAccess:0x000055c690fd5320>):
  
plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:8:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Comment by Loriowar** [comment]
@ashrafalzyoud fixed. Please, fetch latest changes from `4.0.x` branch.
