### ISSUE TITLE
Thin server won't start after plugin installation

### ISSUE THREAD

**Issue by Vritomos** [Loriowar/redmine_issues_tree#12]
I've installed redmine_issues_tree using git clone and after this my thin server simply doesn't start anymore. Since my Redmine version is 2.6.6, from Bitnami, and the plugin have compatibility with 2.6.* version, I believe this shouldn't happen. What could be the problem?

**Comment by Loriowar** [comment]
Issues without complete description of environment, version of language/libs/etc and without full traceback of errors will be rejected immediately.

**Comment by Vritomos** [comment]
Ow.. Sorry for that. Here's the info:

OS: Windows 8

Environment:
 * Redmine version:             2.6.6.stable
 * Ruby version:                  2.0.0-p645 (2015-04-13) [i386-mingw32]
 * Rails version:                   3.2.22
 * Environment:                   production
 * Database adapter:          Mysql2

SCM:
  * Subversion:               1.8.11
  * Git:                            1.9.5
                     
Redmine plugins:
  * timelog_timer                  2.0.0

Error log when I run thin server through cmd:

`>bundle exec rails s -e production`                                             

`DL is deprecated, please use Fiddle`
`DL is deprecated, please use Fiddle`
`=> Booting Thin`
`=> Rails 3.2.22 application starting in production on http://0.0.0.0:3000`
`=> Call with -d to detach`
`=> Ctrl-C to shutdown server`
`Exiting`
`C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/plugins/redmine_issues_tree/init.`
`rb:15:in 'block in <top (required)>': undefined method 'require_patch' for #<Act`
`ionDispatch::Reloader:0x481e5d0> (NoMethodError)`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:429:in '_run__389'`
`983062__prepare__8549960__callbacks'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in '__run_cal`
`lback'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in '_run_prep`
`are_callbacks'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in 'run_callba`
`cks'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/reloader.rb:74:in 'pr`
`epare!'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/reloader.rb:48:in 'pr`
`epare!'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/application/finisher.rb:47:in 'block in <mod`
`ule:Finisher>'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/initializable.rb:30:in 'instance_exec'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/initializable.rb:30:in 'run'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/initializable.rb:55:in 'block in run_initial`
`izers'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/initializable.rb:54:in 'each'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/initializable.rb:54:in 'run_initializers'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/application.rb:136:in 'initialize!'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in 'method_missin`
`g'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/config/environment.r`
`b:14:in '<top (required)>'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/config.ru:3:in 'requ`
`ire'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/config.ru:3:in 'bloc`
`k in <main>'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in 'instance_eval'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in 'initialize'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/config.ru:in 'new'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/config.ru:in '<main>`
`'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in 'eval'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in 'parse_file'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/server.rb:200:in 'app'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/commands/server.rb:46:in 'app'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/server.rb:304:in 'wrapped_app'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/rack-1.4.7/lib/rack/server.rb:254:in 'start'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/commands/server.rb:70:in 'start'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/commands.rb:55:in 'block in <top (required)>`
`'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/commands.rb:50:in 'tap'`
`        from C:/Bitnami/redmine-2.6.6-0/apps/redmine/htdocs/vendor/bundle/ruby/2`
`.0.0/gems/railties-3.2.22/lib/rails/commands.rb:50:in '<top (required)>'`
`        from script/rails:6:in 'require'`
`        from script/rails:6:in '<main>'`

**Comment by Loriowar** [comment]
This plugin require gem `require_patch`. Run bundle, install missed gem and be happy.

**Comment by Vritomos** [comment]
Just installed the gem, but the problem remains the same. I checked the gem list to make sure and it appears right there, as the log shows:

`>gem list`

`*** LOCAL GEMS ***`
`actionmailer (4.2.4, 4.2.3, 4.1.8)`
`actionpack (4.2.4, 4.2.3, 4.1.8)`
`actionpack-action_caching (1.1.1)`
`actionpack-xml_parser (1.0.2)`
`actionview (4.2.4, 4.2.3, 4.1.8)`
`activejob (4.2.4, 4.2.3)`
`activemodel (4.2.4, 4.2.3, 4.1.8)`
`activerecord (4.2.4, 4.2.3, 4.1.8)`
`activerecord-sqlserver-adapter (4.1.0)`
`activesupport (4.2.4, 4.2.3, 4.1.8)`
`arel (6.0.2, 5.0.1.20140414130214)`
`bigdecimal (1.2.0)`
`builder (3.2.2)`
`bundler (1.10.6, 1.7.7)`
`capybara (2.4.4)`
`cgi_multipart_eof_fix (2.5.0)`
`childprocess (0.5.6)`
`coderay (1.1.0)`
`coffee-rails (4.1.0)`
`coffee-script (2.3.0)`
`coffee-script-source (1.8.0)`
`daemons (1.2.3)`
`delayed_job (4.0.6)`
`delayed_job_active_record (4.0.3)`
`docile (1.1.5)`
`erubis (2.7.0)`
`eventmachine (1.0.7)`
`execjs (2.2.2)`
`ffi (1.9.10 x86-mingw32)`
`fullcalendar_engine (1.0.6)`
`gem-path (0.6.1)`
`gem_plugin (0.2.3)`
`globalid (0.3.5)`
`hike (1.2.3)`
`holidays (2.2.0)`
`i18n (0.7.0, 0.6.11)`
`io-console (0.4.2)`
`jquery-rails (4.0.4, 3.1.3, 3.1.2)`
`json (1.8.3, 1.7.7)`
`loofah (2.0.2)`
`mail (2.6.3)`
`metaclass (0.0.4)`
`mime-types (2.6.1, 2.4.3)`
`mini_portile (0.6.2)`
`minitest (5.7.0, 5.4.3, 4.3.2)`
`mocha (1.1.0)`
`mongrel (1.1.5 x86-mingw32)`
`multi_json (1.11.2, 1.10.1)`
`mysql (2.9.1 x86-mingw32)`
`mysql2 (0.3.18 x86-mingw32)`
`net-ldap (0.3.1)`
`nokogiri (1.6.6.2 x86-mingw32)`
`pg (0.17.1 x86-mingw32)`
`protected_attributes (1.1.3)`
`psych (2.0.0)`
`rack (1.6.4, 1.5.2)`
`rack-openid (1.4.2)`
`rack-test (0.6.3, 0.6.2)`
`rails (4.2.3, 4.1.8)`
`rails-deprecated_sanitizer (1.0.3)`
`rails-dom-testing (1.0.6)`
`rails-html-sanitizer (1.0.2)`
`railties (4.2.4, 4.2.3, 4.1.8)`
`rake (10.4.2, 0.9.6)`
`rb-readline (0.5.1)`
`rbpdf (1.18.6)`
`rdoc (4.2.0, 4.0.0)`
`redcarpet (3.1.2)`
`request_store (1.0.5)`
#### `require_patch (0.2.0)`
`rmagick (2.13.4)`
`ruby-ole (1.2.11.8)`
`ruby-openid (2.3.0)`
`rubyzip (1.1.6)`
`sass (3.2.19)`
`sass-rails (4.0.5)`
`selenium-webdriver (2.46.2)`
`simplecov (0.9.1)`
`simplecov-html (0.10.0, 0.8.0)`
`spreadsheet (1.0.5)`
`sprockets (3.2.0, 2.12.3)`
`sprockets-rails (2.3.2, 2.2.1)`
`sqlite3 (1.3.10 x86-mingw32)`
`sqlite3-ruby (1.3.3)`
`test-unit (2.0.0.0)`
`thin (1.6.3)`
`thor (0.19.1)`
`thread_safe (0.3.5, 0.3.4)`
`tilt (1.4.1)`
`tiny_tds (0.6.2 x86-mingw32)`
`tzinfo (1.2.2)`
`tzinfo-data (1.2015.5)`
`websocket (1.2.2)`
`xpath (2.0.0)`
`yard (0.8.7.6)`

The error log remains the same.

**Comment by Loriowar** [comment]
As you see from logs, something goes wrong around `require_patch`. I have no resources for support this plugin under Windows. I guarantee work of plugin within corresponding Redmine version and only under Unix-like systems. So, sorry, but I can't do anything else for you.
If you want, you can joins to me and help with test and improve plugin under Windows.

**Comment by Vritomos** [comment]
Hum, I see... All right, thank you anyway.

**Comment by shipiev** [comment]
require_patch updated, try again
