### ISSUE TITLE
Not working on redmine 4.2.x

### ISSUE THREAD

**Issue by santiagoamo** [Loriowar/redmine_issues_tree#121]
The installation is good, is showing the tree view icon and text, but clicking tree view show an "Internar Error" or entering to an issue.

I try to use the 4.1 version

Environment:
  Redmine version                4.2.2.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x64-mingw32]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.32.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.2
  redmine_issue_templates        1.1.0
  redmineup_tags                 2.0.11

Thanks!

**Comment by Loriowar** [comment]
The log of your 500 error will be really helpful. Most likely there is an incompatibility of the plugin version and Redmine version. Unfortunately, there is no support of Redmine 4.2 version. Other possible source of the problem might be in incompatibility with the installed plugins.

**Comment by santiagoamo** [comment]
THANKS!!

Desintalling the redmineup_tags , works perfecttly!!!

Thanks!!
