### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by AlexShku** [Loriowar/redmine_issues_tree#124]
Hello everyone! I get an error when press button Tree view (https://prnt.sc/23uqiox)

Environment:
  Redmine version                3.4.13.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2

```
ActionView::Template::Error (undefined method `show_value' for #<#<Class:0x00005570103ec350>:0x00005570103eb3d8>
Did you mean?  show_detail):
     6:   <td class="id"><%= link_to issue.to_param, controller: 'issues', action: 'show', id: issue %></td>
     7:   <% # @note: exclude :issue_id column for compatibility with 'issue_id' plugin %>
     8:   <% query.inline_columns.reject { |c| %i(id issue_id).include?(c.name) }.each do |column| %>
     9:     <%= content_tag('td', column_content(column, issue), :class => column.css_classes) %>
    10:   <% end %>
    11: </tr>
    12: <% query.block_columns.each do |column|
  plugins/extended_fields/lib/extended_queries_helper_patch.rb:29:in `column_content_with_extended'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb:9:in `block in _plugins_redmine_issues_tree_app_views_issues_trees__tree_node_html_erb___4466778186943225243_46969896743400'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb:8:in `each'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb:8:in `_plugins_redmine_issues_tree_app_views_issues_trees__tree_node_html_erb___4466778186943225243_46969896743400'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb:26:in `block (2 levels) in _plugins_redmine_issues_tree_app_views_issues_trees__tree_list_html_erb__1107559589787080538_46969896991220'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb:25:in `each'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb:25:in `block in _plugins_redmine_issues_tree_app_views_issues_trees__tree_list_html_erb__1107559589787080538_46969896991220'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb:10:in `_plugins_redmine_issues_tree_app_views_issues_trees__tree_list_html_erb__1107559589787080538_46969896991220'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:38:in `_plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb___3828074526177744474_46969898597520'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by Loriowar** [comment]
Hi, @AlexShku! Have you any other installed Redmine plugins? Maybe, such behaviour is relared with plugins conflict.

**Comment by AlexShku** [comment]
> Hi, @AlexShku! Have you any other installed Redmine plugins? Maybe, such behaviour is relared with plugins conflict.

1. Easy Gantt plugin
2. Easy MindMup plugin
3. Easy WBS plugin
4. Extended fields
5. Lock Out
6. Redcase
7. Redmine Agile plugin (PRO version)
8. Redmine Checklists plugin (Light version)
9. Redmine GitLab Hook plugin
10. Redmine Messenger
11. Require Time Entry Comments
12. Redmine Theme Changer plugin
13. Redmine Timesheet Plugin
14. Redmine Wiki Extensions plugin
15. Redmine Tags plugin (Light version)

I saw a plugin conflict alert with redmineup_tags (https://github.com/Loriowar/redmine_issues_tree/issues/120, and https://github.com/Loriowar/redmine_issues_tree/issues/68#issuecomment-396497466) but found solutions like fix but it didn't solve the problem.

**Comment by Loriowar** [comment]
Yea, there is a wrokaround, but no robust fix. Try to disable redmine_tags. If the tree_view will be fine after that - you know the source of the problem. In such case I'll be glad to  review your PR with the fix.

**Comment by AlexShku** [comment]
> Yea, there is a wrokaround, but no robust fix. Try to disable redmine_tags. If the tree_view will be fine after that - you know the source of the problem. In such case I'll be glad to review your PR with the fix.

There is a problem with module - **extended_fields**
Thanks.
