### ISSUE TITLE
Compatible with Redmine 5.x

### ISSUE THREAD

**Issue by AlexShku** [Loriowar/redmine_issues_tree#127]
Hello! 
Are you planning to adapt your plugin for 5.x Redmine?

**Comment by Loriowar** [comment]
Yea, I have a plan... but I have no ETA :( The main action here is to compare patched views and migrate all changes from Redmine views into plugin.

**Comment by Loriowar** [comment]
@AlexShku hi! Please, try to use a new version of the plugin. It should be compatible with Redmine 5.0. Use corresponding [branch of the plugin](https://github.com/Loriowar/redmine_issues_tree/tree/5.0.x).

**Comment by Interfud** [comment]
NameError: uninitialized constant RedmineIssuesTree::VERSION

  version RedmineIssuesTree::VERSION
                           ^^^^^^^^^
Did you mean?  RedmineIssuesTree::Version
               Version
               Person

**Comment by Loriowar** [comment]
@Interfud du you use new branch `5.0.x` of the plugin? In addition, please, provide current version of Redmine, full backtrace and current branch of the plugin which you're using. Such error happens for plugin for 4.x version, but shoudn't happens for branch `5.0.x`.

**Comment by Interfud** [comment]
root@alex-VirtualBox:/opt/redmine5/plugins# rvm use --default
Using /usr/local/rvm/gems/ruby-3.1.2
root@alex-VirtualBox:/opt/redmine5/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /opt/redmine5)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant RedmineIssuesTree::VERSION

  version RedmineIssuesTree::VERSION
                           ^^^^^^^^^
Did you mean?  RedmineIssuesTree::Version
               Version
               Person
/opt/redmine5/plugins/redmine_issues_tree/init.rb:7:in `block in <top (required)>'
/opt/redmine5/lib/redmine/plugin.rb:96:in `instance_eval'
/opt/redmine5/lib/redmine/plugin.rb:96:in `register'
/opt/redmine5/plugins/redmine_issues_tree/init.rb:3:in `<top (required)>'
/opt/redmine5/lib/redmine/plugin_loader.rb:31:in `load'
/opt/redmine5/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/redmine5/lib/redmine/plugin_loader.rb:108:in `each'
/opt/redmine5/lib/redmine/plugin_loader.rb:108:in `block in load'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
/opt/redmine5/config/environment.rb:16:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.1.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-3.1.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/rvm/gems/ruby-3.1.2/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/application.rb:367:in `require_environment!'
/usr/local/rvm/gems/ruby-3.1.2/gems/railties-6.1.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.1.2/bin/rake:31:in `load'
/usr/local/rvm/rubies/ruby-3.1.2/bin/rake:31:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-3.1.2/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.1.2/bin/bundle:25:in `load'
/usr/local/rvm/gems/ruby-3.1.2/bin/bundle:25:in `<main>'
/usr/local/rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Thank you for your attention!**

**Comment by Interfud** [comment]
Environment:
  Redmine version                5.0.1.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.6

**Comment by tsuyu2016** [comment]
branch
https://github.com/Loriowar/redmine_issues_tree/tree/5.0.x

Environment:
  Redmine version                5.0.2.stable
  Ruby version                   3.1.0-p0 (2021-12-25) [x86_64-linux]
  Rails version                  6.1.6

error from production.log

[ N 2022-09-14 18:12:36.3852 293417/T6 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 293481 output: Error: The application encountered the following error: uninitialized constant RedmineIssuesTree::Version
App 293481 output:
App 293481 output:     parent.const_get(cname, false)
App 293481 output:           ^^^^^^^^^^
App 293481 output: Did you mean?  RedmineIssuesTree::VERSION (NameError)
App 293481 output:     /var/www/html/redmine-5.0.2/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
App 293481 output:     /var/www/html/redmine-5.0.2/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
App 293481 output:     /var/www/html/redmine-5.0.2/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
App 293481 output:     /var/www/html/redmine-5.0.2/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
App 293481 output:     /var/www/html/redmine-5.0.2/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'

**Comment by Loriowar** [comment]
@Interfud thanks for details. I found the problem. Try to use the latest version of `5.0.x` branch. There is fix for the issue.

**Comment by tsuyu2016** [comment]
@Loriowar 
Could you help me how to resolve this problem?
https://github.com/Loriowar/redmine_issues_tree/issues/127#issuecomment-1246483579

**Comment by Loriowar** [comment]
@tsuyu2016 is this still reproducable with latest `5.0.x` branch of the plugin? Problem with `uninitialized constant` should be fixed in the latest patch.

**Comment by tsuyu2016** [comment]
@Loriowar 
Thank you ver much! 
It's OK!

**Comment by Loriowar** [comment]
Seems like all works fine. Closed.

**Comment by AlexShku** [comment]
Hello! I find an issue with the bulk edition - pop-up with NO URL (https://prnt.sc/Ba3YNWiocGzp)
Does anyone has the same error?

**Comment by Loriowar** [comment]
@AlexShku if you've found a bug, please, create new issue, describe your env and provide the steps for reproduce it.
