### ISSUE TITLE
How to download Redmine 2.6.9  for Windows 10 

### ISSUE THREAD

**Issue by Cat0and0Dog** [Loriowar/redmine_issues_tree#129]

**Comment by Loriowar** [comment]
As I see from the theme this is not related with plugin. So, you can use [Google](https://www.google.com/search?q=redmine+windows+10) and [official Redmine installation guide](https://www.redmine.org/projects/redmine/wiki/redmineinstall). For usage of the plugin just use correponding branch. For your case with 2.6.9 Redmine the branch [2.6.6](https://github.com/Loriowar/redmine_issues_tree/tree/2.6.6) should works fine.
