### ISSUE TITLE
click tree view goes to 505 page

### ISSUE THREAD

**Issue by peterdu88** [Loriowar/redmine_issues_tree#13]
Redmine 3.0
Ruby 2.1.6p336
Ubuntu 14.04

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Production.log

  Tracker Load (0.3ms)  SELECT DISTINCT `trackers`.* FROM `trackers` INNER JOIN `projects_trackers` ON `projects_trackers`.`tracker_id` = `trackers`.`id` INNER JOIN `projects` ON `projects`.`id` = `projects_trackers`.`project_id` JOIN enabled_modules ON enabled_modules.project_id = projects.id AND enabled_modules.name = 'issue_tracking' WHERE (projects.lft >= 11 AND projects.rgt <= 12 AND projects.status <> 9)  ORDER BY `trackers`.`position` ASC
Completed 500 Internal Server Error in 22ms (ActiveRecord: 1.6ms)

NoMethodError (undefined method `<<' for {}:Hash):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by Loriowar** [comment]
Need more info (preferable a full traceback). Now I can't imagine how plugin involved in this situation.

**Comment by peterdu88** [comment]
What do you need?

**Comment by Loriowar** [comment]
Need full traceback(i.e. callstack) of 500 error for understanding how my plugin influence on your app.

**Comment by Loriowar** [comment]
Are you using an issue query with grouping condition? Or have you a SCRUM plugin in your Redmine installation?

**Comment by Loriowar** [comment]
Not enough information.
