### ISSUE TITLE
Tree view button not visible after installation

### ISSUE THREAD

**Issue by jamescorn** [Loriowar/redmine_issues_tree#16]
Hi!
I installed this plugin on my redmine 3.1.2. After installation  nothing changed in issues view, there isn't any Tree view buttons on the top right. I made the installation as you described.
My Ruby version: 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux-gnu]
And I download the 3.1.0 branch.

What did I do wrong?
If you need any further information, please tell me.

Thanks!

**Comment by Loriowar** [comment]
One of the reason is follows: you have other plugins, which redefine `issues/index` template.  In this case you need to manually add hooks for my plugin. List of required hooks you can find in [plugin description](https://github.com/Loriowar/redmine_issues_tree#features).

**Comment by jamescorn** [comment]
Now it's working.
I inserted the missing hooks into index.html.erb, then reinstall the master branch instead of 3.1.0. Then run bundle install again, and now the tree view button is visible :)

Thank you for your help!

**Comment by Loriowar** [comment]
Thanks for using this plugin! Glad to help.
