### ISSUE TITLE
Can't not show Tree View icon

### ISSUE THREAD

**Issue by hello2jack** [Loriowar/redmine_issues_tree#18]
After update to Redmine version 3.0.7, can't not show Tree View icon in the issue tab.
![image](https://cloud.githubusercontent.com/assets/14246273/12045140/213a788e-aed0-11e5-8283-ace3345b140c.png)

Environment:

Name|Version
------------ | -------------
Redmine version|3.0.7.stable
Ruby version|1.9.3-p551 (2014-11-13) [x86_64-linux]
Rails version|4.2.3
Environment|production
Database adapter|Mysql2

SCM:

Name|Version
------------ | -------------
Subversion|1.7.14
Git|1.8.3.1
Filesystem|

Redmine plugins:

Name|Version
------------ | -------------
a_common_libs|2.0.0
clipboard_image_paste|1.10
extra_queries|2.0.3
localizable|0.4.0
manage_wiki_view_page_permission|0.0.1
progressive_projects_list|2.0.1
quick_view|0.1.0
redmine_agile|1.3.12
redmine_banner|0.1.1
redmine_checklists|3.1.3
redmine_contacts|4.0.4
redmine_documents_short|0.3.0
redmine_group_owners|2.0.0
redmine_issue_tabs|1.1.1
redmine_issue_templates|0.1.1
redmine_issues_tree|0.0.6
redmine_knowledgebase|3.1.0
redmine_ldap_sync|2.0.6
redmine_lightbox2|0.2.4
redmine_logs|0.1.0
redmine_theme_changer|0.2.0
redmine_wiki_extensions|0.7.0
redmine_work_time|0.3.1
release_logs|1.0.0
rmp_group_watchers|1.0.0
sidebar_hide|0.0.7
usability|2.0.0

**Comment by Loriowar** [comment]
Looks like one of the plugin redefine a default template `issues/index`. Similar problem appear in #16. So, you must look on all your plugin, find all redefinition of this template, select last of them (according with order of plugin loading) and add a hooks into it. List of hooks you can find in ReadMe of plugin and/or in source code.
And sorry, but there is no good or universal way of solution of this problem. This is Redmine.

**Comment by hello2jack** [comment]
Hi @Loriowar , thanks for your suggest, but i don't know how to fix it. :(

**Comment by Loriowar** [comment]
Strange... Absence of links can happen only in two cases: broken mechanism of the Redmine hooks or multiple redefinition of the template. On pure Redmine 3.0.7 plugin works perfect. So, need more information about your installation or any other help in investigation. Anyway, I'll be glad to fix it and make a plugin better.

If you use a custom sequence of loading plugin, please, show me this sequence.

**Comment by hello2jack** [comment]
Hi @Loriowar , i find out the problem, is plugin compatibility issue, after remove http://rmplus.pro/ "extra_queries	2.0.3", the Issue Tree will be work fine.

![image](https://cloud.githubusercontent.com/assets/14246273/12131986/f57c6a8e-b449-11e5-9d49-97f6aeb62a49.png)

**Comment by Loriowar** [comment]
Yea, I see. Extra_queries redefine a template `issue/index`. This template located in `extra_query/app/views/extra_queries/issues/index.html.erb`. So, you must add two hooks from `redmine_issues_tree/app/views/issues/index.html.erb`. Look at rows inside my plugin which commented as follows

    <%# issues_tree patch %>
    ...
    <%# end patch %>

And add them into `extra_queries` template into proper places. This will solve problem with "tree view" icon. But remember, what you can't see extended variant of issue queries on tree view page. There appear default variant of queries.

So, if you want use advantages of both plugins, you need to find someone who will write new plugin, based on "extra_queries" and "redmine_issues_tree". Redmine is absolutely nonflexible system in case of extensions especially in plugins compatibility.
