### ISSUE TITLE
Problem (redmine 2.6.9)

### ISSUE THREAD

**Issue by Holland-Dexter** [Loriowar/redmine_issues_tree#19]
Hello Loriowar!

We introduce redmine in our production process, and your plugin is extremely useful
for our purposes.

I installed the plugin as described in the installation manual:
*  copied the source code of plugin (2.6.6) into the folder `\\redmine\apps\redmine\htdocs\plugins\`;
*  installed required gems;
*  web-server restarted.

After that plugin appears in the list, but didn't start work.
I guess the problem is in hooks.

I tried to copy the content of the plugin folder `app\`  in the same redmine folder  - it didn't help.

Plesase tell me how to implement hooks correctly.

I hope you can help me.

#### Environment

    Ubuntu 9.0.4
    Redmine version   2.6.9.stable
    Ruby version   2.0.0-p647 (2015-08-18) [i686-linux]
    Rails version   3.2.22
    Environment   production
    Database adapter   Mysql2

    SCM:
      Subversion   1.8.13
      Git   2.6.1
                      
    Redmine plugins:
      redmine_issues_tree            0.0.6

**Comment by Loriowar** [comment]
Hello! Your destination folder for plugins looks strange. By default, plugins located in `.../redmine/plugins` and path for `redmine_issues_tree` must looks as follow: `.../redmine/plugins/redmine_issues_tree`. In this variant all works perfect.
Anyway, copying part of plugins is wrong approach.

**Comment by Holland-Dexter** [comment]
Loriowar, thanks for your reply!

The fact is that I use BitNami Redmine Stack.
That is what is written in the Bitnami Redmine FAQ:

    ...
    The applications in Bitnami are installed in the 'apps' folder that you can find in the installation
    directory.
    ...
    The main folders that you can find inside 'apps/redmine' are the following:
     * conf: folder that includes the apache configuration files for redmine
     * htdocs: this folder includes the redmine files (Gemfile and Rakefile files, redmine configuration
    files, plugins folder, gems, etc).
    The location of the redmine configuration files (database configuration, email settings, etc) is the
    'apps/redmine/htdocs/config' folder.
    ...
        Download the plugin and copy the directory into installdir/apps/redmine/htdocs/plugins.
By the way, your plugin is displayed in the Redmine plugins list:

![image 2](https://cloud.githubusercontent.com/assets/16663805/12415533/43abc480-bead-11e5-902c-9eae10a47844.png)

What do you think, is it possible to run redmine_issues_tree on this configuration?

**Comment by Loriowar** [comment]
Look at #20 issue. Maybe this help you. I have not an experience with BitNami, so I can't say something important in this direction.
