### ISSUE TITLE
Tree view only available on some issues

### ISSUE THREAD

**Issue by jmalsoaz** [Loriowar/redmine_issues_tree#22]
First of all, I would like to thank you for your work on the plugin,

I'm very interesting in using it but unfortunately, it is not fully working on my redmine. I'm using Redmine 3.2.0.

The tree view is only working for some issues. But not all issues with subtasks show the small icon to expand tree. Is there any reason ? Related to the issue tracker / status ? I can't find any correlation.

Thank you for your help.
Best

**Comment by Loriowar** [comment]
You must see all available issues if you open "Tree view" without any query conditions. In case of specifying query, plugin try to extract parts of tree from result of query. And finally, plugin show only subtask, i.e. plugin ignore all other relations, for example "copy from", "related with" and so on. So, if you see issues in plain view and can't find them in tree view, provide me more information about your installation, installed plugins and about relations of the issues. I'll try to find a problem and fix it.

**Comment by jmalsoaz** [comment]
Thank you for your help.

Please see enclosed a view of my issues. Each displayed issue has at least one subtask. However, expand is only available for a few. Same thing append with no filter selected.

![requirements_view](https://cloud.githubusercontent.com/assets/16926441/12639399/71e52532-c5a4-11e5-841d-426619aefac5.png)

Regarding my installation, please see the following  version number with plugins as well.
![redmine](https://cloud.githubusercontent.com/assets/16926441/12639503/051f5b74-c5a5-11e5-909e-c5900f6d1ce0.png)

**Comment by jmalsoaz** [comment]
By the way, I have just tested with a new project and new issues. It is working like a charm.

Is there a problem with previous saved issues ?

**Comment by Loriowar** [comment]
Sometime appears a problem with saved queries. Most frequently this happens in case of "group by" condition in query. But all reasons are unknown for now. What about inheritance scheme of issues, I don't know any problem with it. If new issues works perfect, then you need to look at correctness of existing data, there is a high probability of corruption.
Another reason can be found in changing of issues behaviour by other plugins. In this case can appear floating errors and/or incompatibility between plugins. So, this is Redmine and anything is possible.
