### ISSUE TITLE
Can not save Tree view

### ISSUE THREAD

**Issue by rmaugusto** [Loriowar/redmine_issues_tree#23]
After changed to 'Tree view' even applying it seems that it is not saving. When I open issues again the plain structure comes back.

**Comment by Loriowar** [comment]
Sorry, but not enough information for analysis. Provide me a logs from webapp, tell me about situation in js console of the browser, provide me information about your environment, versions of Ruby and other gems and so on. In this case I can try to help you and say what happens.

**Comment by bluenevus** [comment]
same problem here.  I have to click tree view every time I want to use it.  the state doesn't save.  in fact, I rather that be the default state so every user sees it and the default view and has to click plain structure to change it back

**Comment by Loriowar** [comment]
Oh, now I understand you. This feature described in #8. There is more details about problem with this solution. So, any thoughts you can describe in that issue. This task closed as duplicate.
