### ISSUE TITLE
Support for Redmine 3.2.0

### ISSUE THREAD

**Issue by clkrueger** [Loriowar/redmine_issues_tree#25]
Our organization would like to use your plugin but it's not compatible with Redmine 3.2.0.  Our ops developer installed the version for 3.1.0 and reported UI issues with the views.  Here is one item that he reported  "pagination controls for the issues list has turned into radio buttons".

Any chance you will support 3.2.0?

Thanks,
Connie

**Comment by Loriowar** [comment]
Yes, my main aim to support plugin for last actual version of Redmine. So, I'll try to make it compatible with Redmine 3.2.0 in a closest future.

**Comment by Loriowar** [comment]
I tested a plugin and it's perfect works under Redmine 3.2.0. You can use `master` or `3.2.x` branch. Honestly speaking, `3.1.0` works with Redmine 3.2.0 too.

What about your "pagination" question: as I understand, you want to have a pagination system on tree view. If so, then I can disappoint you. For now, there is no any pagination for tree view of issues. This behavior goes from ambiguity of algorithm for pagination. If you can provide a clear one, then I can implement this. Or you can make a pull request and I'll be glad to discuss and merge it. Anyway, please, correct me if I misunderstand you question.

**Comment by clkrueger** [comment]
Ivan,

When the plugin was added to our Redmine installation this is what the
developer told me "the pagination controls for the issues list has turned
into radio buttons".  So your plugin is breaking the existing pagination.
So our developer will not use 3.1.0.

Connie

**Comment by Loriowar** [comment]
Plugin completely skip pagination on issues tree, but do nothing with pagination on plain (default) issues list. This is a feature, not bug. If your developers found something strange, please, invite them into this theme. They can completely describe situation and provide information about situation and environment. I'm interested in support and improving of plugin, but not in implementation of functions for purposes of single installation.

**Comment by monakov-y** [comment]
Hi, @Loriowar!

First of all I want to say this plugin is really great.

I have the same issue as @clkrueger, but I can explain this further. Redmine 3.2 and 3.3 has new pagination style with som kind of buttons instead of raw links:

**Comment by monakov-y** [comment]
Ooops, I'm sorry. This is not an issue with master and 3.3.x branches.
