### ISSUE TITLE
Redmine. Error 500 - Issue tree 0.0.7

### ISSUE THREAD

**Issue by hello2jack** [Loriowar/redmine_issues_tree#26]
When i installed 0.0.7, in issue list will show Error 500.

undefined method `available_totalable_columns_tags' for #<#<Class:0x007f62773c4bb0>:0x00000005064b18>
---

Environment:
  Redmine version                3.1.4.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.1.6
  clipboard_image_paste          1.10
  localizable                    0.4.0
  manage_wiki_view_page_permission 0.0.1
  redmine_checklists             3.1.3
  redmine_contacts               4.0.4
  redmine_dmsf                   1.5.6
  redmine_documents_short        0.3.0
  redmine_group_owners           2.0.0
  redmine_issue_tabs             1.1.1
  redmine_issue_templates        0.1.1
  redmine_issues_tree            0.0.7
  redmine_knowledgebase          3.1.0
  redmine_ldap_sync              2.0.6
  redmine_lightbox2              0.2.5
  redmine_people                 1.2.0
  redmine_theme_changer          0.2.0
  redmine_wiki_extensions        0.7.0
  redmine_work_time              0.3.1
  release_logs                   1.0.0
  rm_user_mentions               1.0.0
  usability                      2.1.2

---

Error log

        /var/www/redmine/plugins/redmine_issues_tree/app/views/issues/index.html.erb:52:in `block in _plugins_redmine_issues_tree_app_views_issues_index_html_erb___1230572474742404658_32190180'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/usr/local/rvm/gems/ruby-2.2.3/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/usr/local/rvm/gems/ruby-2.2.3/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/helpers/form_tag_helper.rb:70:in `form_tag'
/usr/local/rvm/gems/ruby-2.2.3/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:125:in `form_tag_with_haml'
/usr/local/rvm/gems/ruby-2.2.3/gems/haml-4.0.7/lib/haml/helpers/action_view_xss_mods.rb:18:in `form_tag_with_haml_xss'
/var/www/redmine/plugins/redmine_issues_tree/app/views/issues/index.html.erb:19:in `_plugins_redmine_issues_tree_app_views_issues_index_html_erb___1230572474742404658_32190180'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:46:in `render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:27:in `render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:100:in `_render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/abstract_controller/rendering.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
/var/www/redmine/app/controllers/issues_controller.rb:77:in `block (2 levels) in index'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/mime_responds.rb:217:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
/var/www/redmine/app/controllers/issues_controller.rb:76:in `index'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:313:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/www/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:312:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:137:in `process'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:30:in `process'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:196:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:237:in `block in action'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.0.26/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by Loriowar** [comment]
In `master` branch located changes for last Redmine version. For now this is a Redmine 3.2. If you use any lower version, please, use corresponding branch of plugin. For you installation this is a branch `3.1.0`. This organization of repository describred in [Readme](https://github.com/Loriowar/redmine_issues_tree#usage).
