### ISSUE TITLE
(undefined method `available_totalable_columns_tags' ERROR

### ISSUE THREAD

**Issue by hamdijmii1992** [Loriowar/redmine_issues_tree#27]
When I tried to acces my issues page , I found this error !!

ActionView::Template::Error (undefined method `available_totalable_columns_tags' for #<#<Class:0x007f915c43a2e8>:0x007f915c438880>):
    49:           </tr>
    50:           <tr>
    51:             <td><%= l(:label_total_plural) %></td>
    52:            <td><%= available_totalable_columns_tags(@query) %></td>
    53:           </tr>
    54:         </table>
    55:       </div>
  app/controllers/issues_controller.rb:87:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:86:in `index'

same help please !!

**Comment by Loriowar** [comment]
There is high probability, that you clone `master` branch of plugin and try to use it for Redmine with version 3.1.0 or less. If so, please, look at [Readme](https://github.com/Loriowar/redmine_issues_tree#usage) and use corresponding branch of plugin. Master branch is not for production usage.

**Comment by hamdijmii1992** [comment]
thanks ,you are right
