### ISSUE TITLE
Plugin not generating h2 tag

### ISSUE THREAD

**Issue by carukc** [Loriowar/redmine_issues_tree#3]
Hello,

Cool plugin... Thanks for writing!

I've been trying to use with the Pixel Cookers theme and have noticed that something is happening to the title and tab when displaying the tree view.

This is the normal:

![image](https://cloud.githubusercontent.com/assets/1935704/9736161/94fc36a0-5637-11e5-9356-73e58dd40f22.png)

This is the tree view:

![image](https://cloud.githubusercontent.com/assets/1935704/9736217/d7d1b158-5637-11e5-805e-5d9f147ced73.png)

I've checked the CSS and it seems to be the same in both cases.  

I think that I have tracked the problem down to how the heading is generated.  The normal view (app/views/issues/index.html.erb") generates:

    <h2>>Actions<\h2>

and the plugin view (plugins/redmine_issues_tree/app/views/issues/index.html.erb) generates:

    <br><br>

I think the view code that generates this is:

    <h2><%= @query.new_record? ? l(:label_issue_plural) : @query.name %></h2>
    <% html_title(@query.new_record? ? l(:label_issue_plural) : @query.name) %>

but for some reason the heading does not appear.

I'm new to ruby but would be pleased to assist if you could help point me in the right direction.

Many Thanks
Chris

**Comment by Loriowar** [comment]
Removed <br> from master and from 3.* branches. Moreover redefinition of templates and partials turned to maximal matching with default variants. Please check, is this works now?

**Comment by carukc** [comment]
Works great!  Thanks

Do you think that there might be a way to make this the default view?  Perhaps an option in project settings that enables a check within the view and switchs automatically if set?

Thanks Again
Chris

**Comment by Loriowar** [comment]
You are welcome! Thanks for using of my plugin.

There is no difficulties to make this view as default one for issues list. But this tree view have several lacks: there is no pagination and it may take lots of time for loading all issues in project and it can't handle grouping of issues. So, for now, I don't want to add described options into project settings. Maybe in future, when I implement an alternative for pagination of the tree view.
