### ISSUE TITLE
Tree view only available for project-scoped issues

### ISSUE THREAD

**Issue by iamvanja** [Loriowar/redmine_issues_tree#30]
Hi, 

First of all thanks so much for this awesome plugin. We heavily rely on parent-child relationships for our tickets and this plugin is a huge upgrade in terms of seeing them.
However, we've noticed that it works only when issues are scoped to a project (`/projects/<project-name>/issues_trees/tree_index`), but not for all issues (`/issues_trees/tree_index`). 

Is this by a design and/or is there a workaround?

Version: 3.2.1, bitnami-redmine

Thanks

**Comment by Loriowar** [comment]
Honestly speaking, I don't thought about issues list without project scope. For a first view, there is no any limitation for this feature. So, I try to do that in future. Thanks for idea.

**Comment by Loriowar** [comment]
Available in new version `0.0.10`, but only for Redmine 3.x (support of features for Redmine 2.x is over). Please, update you plugin.
