### ISSUE TITLE
Compatible with Redmine 3.3.0?

### ISSUE THREAD

**Issue by danboh** [Loriowar/redmine_issues_tree#35]
Hello, and thank you for this plugin.

We're looking to implement it in our current 3.3.0 environment, but would like to know if it's compatible or not, or if you'll be releasing a new version any time soon?

Thanks!

**Comment by Loriowar** [comment]
This plugin not tested on compatibility with Redmine `3.3.x`. But, as I know, there is no major differences between Redmine `3.2.x` and `3.3.x` in part of issues views and partials. So, there is high probability of working plugin from branch `3.2.x` with Redmine `3.3.0`. From my side, I'll try to test plugin for compatibility and make all needed changes within next week.

**Comment by danboh** [comment]
Thank you. I could try to install it in my working 3.3.0 testing environment, but I'm having some trouble following your instructions. What exactly do I need to copy where?

Thanks again

**Comment by Loriowar** [comment]
As described in [installation section](https://github.com/Loriowar/redmine_issues_tree#installation). You must clone branch `3.2.x` from this repo into folder with your Redmine, for example `.../redmine/plugins/`. Then run `bundle`, restart webapp server and thats all.

**Comment by danboh** [comment]
Thank you! I was able to install it, and it seems to be working ok.

**Comment by Loriowar** [comment]
Now plugin officially compatible with Redmine 3.3.0. Use branch `3.3.x` for this.

**Comment by danboh** [comment]
Thank you. Any particular changes from branch 3.2.x? We have been using this one in our 3.3.0 installation without any issues.

**Comment by Loriowar** [comment]
You can look at commit fb3ea362146f195127722a5ad9ec04a2c149b7f2 . In short: several changes on index page related with "New issue" button and with query actions.
