### ISSUE TITLE
Layout broken but only in some projects

### ISSUE THREAD

**Issue by aarkayna** [Loriowar/redmine_issues_tree#36]
Hi there,

I am really appreciating this plugin. I have been using it very successfully on one of our projects but we do have a very strange rendering issue.

Here is an example of when it works and when it doesn't:

Project A
- My MacBook Pro (Safari and Chrome) everything renders just fine
- Team members Linux desktop checkbox columns are missing from parent issues

Project B
- My MacBook Pro (Safari and Chrome) checkbox columns are missing from parent issues
- Team members Linux desktop checkbox columns are missing from parent issues

Here is an image of when the rendering is correct:

![screen shot 2016-08-09 at 1 11 13 pm](https://cloud.githubusercontent.com/assets/13950284/17531895/c96d5190-5e32-11e6-86c7-033ab5b65348.png)

Here is an image of the same project when the rendering is incorrect:

![pastedimage](https://cloud.githubusercontent.com/assets/13950284/17531878/ad574b0a-5e32-11e6-94ca-d052ec21f6df.png)

**Comment by Loriowar** [comment]
Interesting...looks like you have different params with list of displayed columns for `tree_index` and for `tree_children` actions. May you provide development logs with requests to these two actions in the moment when you see an mismatch?

Other variant: someone or somehow you received cached response on tree level expand action.

Anyway, I need an instruction how to  repeat this behaviour or I need an log information about all actions involved in mismatch.

**Comment by Loriowar** [comment]
No responce for a long time. Closed.

**Comment by Loriowar** [comment]
No responce for a long time. Closed.
