### ISSUE TITLE
 but under 2.5 it doesn't work

### ISSUE THREAD

**Issue by wangshengshun** [Loriowar/redmine_issues_tree#4]
Very good and useful plugin, but under 2.5 it doesn't work.
Will you adapt it for 2.5?
Thanks.

**Comment by Loriowar** [comment]
Yes, I planning to adopt the plugin for older versions of the Redmine. But this is not a primary target. It is quite difficult to implement features in all supported versions. That is why my aim is implementation of new features for Redmine 3 and later. For now, there is no major differences in source code of different versions of the plugin. So, you can try to migrate it by yourself. I'll be glad to make a new branch for your working version of this plugin.

**Comment by wangshengshun** [comment]
thank you ！
I am looking forward to a branch you can do to support redmine2.5 and following versions, because many are in use redmine2.5 version and the following version, it is expected that you can do to meet the needs of a single branch, thank you！

**Comment by Loriowar** [comment]
I tested `2.6.6` version of the plugin with Redmine `2.5.3` and it works fine. So, I created separate branch for version of the plugin compatible with Redmine `2.5.3`. Now you can use it in your project.

**Comment by wangshengshun** [comment]
Thank you very much! Loriowar, I just downloaded a try here, you develop this plugin really solve the problems we showcase project tasks and subtasks parent, I try here!

**Comment by wangshengshun** [comment]
Hello, Loriowar, I experiment a bit here, and I execute the following command:
? [31mCould not find gem 'require_patch (~> 0.1.0) x86-mingw32' in the gems avail
able on this machine.? [0m
? [33mRun `bundle install` to install missing gems.? [0m, you look over there to help me, thank you, Loriowar

**Comment by Loriowar** [comment]
Here is this gem [require_patch](https://rubygems.org/gems/require_patch/versions/0.0.7). I don't know what troubles you have with it. Looks like you work under Windows. If it so, I can't help you due to absence of any knowledge in working under this OS. I tested all versions of plugin only on pure Redmine under Unix system.
