### ISSUE TITLE
Not able to update the plugin in bitnami redmine 3.2 and 3.3

### ISSUE THREAD

**Issue by mmanoharan83** [Loriowar/redmine_issues_tree#44]
Plugin Name: redmine issue tree plugin 

redmine_issues_tree-3.3.x is updated in bitnami redmine stack.

Issue Details:
===============
bitnami stack version: bitnami redmine-3.3.1-0

Updated path: apps/redmine/htdocs/plugins

Eaxmple: /opt/redmine-3.3.1-0/apps/redmine/htdocs/plugins

Apache Restart in bitnami redmine
================================
[root@nms031 redmine-3.3.1-0]# pwd
/opt/redmine-3.3.1-0
[root@nms031 redmine-3.3.1-0]# ./ctlscript.sh restart apache
env: monit: No such file or directory
Syntax OK
/opt/redmine-3.3.1-0/apache2/scripts/ctl.sh : httpd stopped
Syntax OK
/opt/redmine-3.3.1-0/apache2/scripts/ctl.sh : httpd started at port 4500
env: monit: No such file or directory
[root@nms031 redmine-3.3.1-0]# 

Observations:
=================
After update of plugin, not able to login from web page.
![screenshot](https://cloud.githubusercontent.com/assets/17979939/20874071/9674c38c-bad4-11e6-8c85-e73ea35a87d6.png)

**Comment by mmanoharan83** [comment]
Kindly suggest the correct way of updating this plugin in bitnami redmine stack

**Comment by Loriowar** [comment]
Sorry, but I don't know details about update in bitnami. I can suppose, what you can go into `/opt/redmine-3.3.1-0/plugins/redmine_issues_tree` and manually switch a branch to `3.3.x`.

**Comment by mmanoharan83** [comment]
Required apache2 logs are attached.

Path: /opt/redmine-3.3.1-0/apache2/logs

[root@nms031 redmine-3.3.1-0]# pwd
/opt/redmine-3.3.1-0
[root@nms031 redmine-3.3.1-0]# 
[root@nms031 redmine-3.3.1-0]# tail -f  apache2/logs/*
==> apache2/logs/error_log <==
App 9255 stdout: 
App 9255 stdout: 
[ 2016-12-07 13:00:14.1950 9159/7f630c7ab700 App/Implementation.cpp:287 ]: Could not spawn process for application /opt/redmine-3.3.1-0/apps/redmine/htdocs/: An error occured while starting up the preloader.
  Error ID: b63f4924
  Error details saved to: /tmp/passenger-error.Lt1rEr
  Message from application: undefined method `require_patch' for #<ActionDispatch::Reloader:0x007f3be258ef60> (NoMethodError)
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/plugins/redmine_issues_tree/init.rb:15:in `block in <top (required)>'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /opt/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `eval'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:111:in `preload_app'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:157:in `<module:App>'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /opt/redmine-3.3.1-0/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/helper-scripts/rack-preloader.rb:28:in `<main>'


[ 2016-12-07 13:00:14.2526 9159/7f630e5ef700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is b63f4924. Please see earlier logs for details about the error.

==> apache2/logs/access_log <==
127.0.0.1 - - [07/Dec/2016:13:00:00 +0530] "GET /redmine/ HTTP/1.1" 500 3065

**Comment by mmanoharan83** [comment]
Plugin Update Steps for above logs
====================================
[root@nms031 plugins]# pwd
/opt/redmine-3.3.1-0/apps/redmine/htdocs/plugins
[root@nms031 plugins]# 
[root@nms031 plugins]# git clone https://github.com/Loriowar/redmine_issues_tree.git
Cloning into 'redmine_issues_tree'...
remote: Counting objects: 426, done.
remote: Total 426 (delta 0), reused 0 (delta 0), pack-reused 426
Receiving objects: 100% (426/426), 63.61 KiB | 79.00 KiB/s, done.
Resolving deltas: 100% (202/202), done.
Checking connectivity... done.
[root@nms031 plugins]# ls
README  redmine_issues_tree
[root@nms031 plugins]# cd redmine_issues_tree/
You have new mail in /var/spool/mail/root
[root@nms031 redmine_issues_tree]#
[root@nms031 redmine_issues_tree]# git branch
* master
[root@nms031 redmine_issues_tree]# git checkout 3.3.x
Branch 3.3.x set up to track remote branch 3.3.x from origin.
Switched to a new branch '3.3.x'
[root@nms031 redmine_issues_tree]# git branch
* 3.3.x
  master
[root@nms031 redmine_issues_tree]#

**Comment by Loriowar** [comment]
Looks like you do not run `bundle` in the Redmine root directory.

**Comment by mschuckmann** [comment]
I'm having the same problem I can't get the plugin to install for Redmine 3.2.x on a Bitnami. 

You're installation instructions assume that I know something about Ruby and I don't. 
The only instruction you give is to run 'bundle install' but where do I run this? 

If I run it in the /opt/bitnami/apps/redmine/htdocs directory I get the following error: 
```
bitnami@redmine:/opt/bitnami/apps/redmine/htdocs$ bundle install
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the Gemfile freeze 
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* haml-rails
* require_patch (~> 0.1.0)
```
I get the same error if I run it in the plugins directory. 

If I run it in the plugins/redmine_issues_tree directory I get this error: 
```
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this
to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'haml-rails (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on this
machine.
```

Can you give any recommendations on what needs to be done?

**Comment by Loriowar** [comment]
You already have all recommendations in error message. Use common sense and Google. This error can be solved during couple minutes.

Description of installation process is enough only for installations of the plugin on a pure Redmine. In other case you best know your installation and you must know that to do. And yes, I suppose that plugin will be installed only by web-developers or someone else with basic knowledge of Ruby and a related area.

**Comment by mschuckmann** [comment]
I'm sorry but that's a very poor response, I've installed several other plugins and not experienced this issue and the standard plugin install method doesn't reference anything about running bundle install so a little explicit help really isn't too much to ask.  

So which recommendation error messages should I pay attention to the one recommending that I modify a Gemfile in I presume your source code or the one that recommends that I check in a changed Gemfile.lock into some none existent version control.

**Comment by Loriowar** [comment]
I developed a plugin, I tested this on pure Redmine and I guarantee a works of plugin under this conditions. Described problem is not a problem of plugin, this is you local problem of installation. I can help with any problem, related with plugin functions. But the problem of your local installation is completely yours. How to install gems and other dependencies of RoR app described on corresponding page of Rails project and on StackOverflow.

Related links:
 - [Google result](https://www.google.com/search?q=Your+Gemfile+has+no+gem+server+sources.&ie=utf-8&oe=utf-8)
 - [About source from bundler site](http://bundler.io/v1.1/gemfile.html)
 - [One more Google](https://www.google.com/search?q=You+are+trying+to+install+in+deployment+mode+after+changing+your+Gemfile.&ie=utf-8&oe=utf-8)
 - [And StackOverflow about Gemfile and Gemfile.lock problem](http://stackoverflow.com/questions/11513623/bundler-you-are-trying-to-install-in-deployment-mode-after-changing-your-gemfil)
