### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by destiny931** [Loriowar/redmine_issues_tree#46]
I am using Redmine 3.3.1.  I downloaded and copied redmine_issues_tree to my plugins directory.  Next I ran bundle install and GEM files were added. Afterwards I logged into redmine and did not see a tree view.  If I restart Redmine, the thin_redmine and thin_redmine2 will not start. Am I missing anything with the installation?

**Comment by Loriowar** [comment]
This may occur by many reasons, for example:
* did you have installed other plugins? Maybe this plugins redefined the `issues/index` template;
* wrong directory of installation (did you see an information about plugin into Redmine admin panel?);
* did you install proper branch of the plugin? (`3.3.x` in your case)

**Comment by Loriowar** [comment]
No responce for a long time. Closed.

**Comment by Loriowar** [comment]
No responce for a long time. Closed.
