### ISSUE TITLE
does it conflict with 

### ISSUE THREAD

**Issue by archonwang** [Loriowar/redmine_issues_tree#47]
@Loriowar 

I used the redmine_issues_tree (https://github.com/charleneChen/redmine_issues_tree_view) also, does it conflict each other? 
Thanks.

![image](https://cloud.githubusercontent.com/assets/834512/23638580/67b27792-031d-11e7-9e8e-a2268aa978e4.png)

**Comment by archonwang** [comment]
my environment is 

> Environment:
>   Redmine version                3.3.2.stable.16377
>   Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2

**Comment by Loriowar** [comment]
As I can see, you must select only one of this plugins due to incompatibility.

**Comment by archonwang** [comment]
@Loriowar 
Thanks for your reply, but unfortunately, I have installed two plugin and start the app server and run for some time.  How can I fix the style problem. when issues have subtask, it seems not good~~
do you have any idea?

**Comment by Loriowar** [comment]
In current Redmine architecture you have two ways: improve one of this plugins and remove other one or write new one for fix incompatibility.

**Comment by archonwang** [comment]
@Loriowar , Thanks.
I tried to remove the plugin and the cache, but still have the same problem..

or anything I have missed?

**Comment by Loriowar** [comment]
Very strange. Separately plugins must work well.

There is no any specifically actions for removing. Simple remove a directory with plugin and restart web-app. A probably reason can be in using a assets pipeline. But for Redmine this one disable by default. So, if you have enabled pipeline, you must recompile assets. I don't know other variants of this behaviour. If you can find a reason, please, say about that. Otherwise I try to repeat this locally.

**Comment by archonwang** [comment]
@Loriowar  Thanks.  I will tried it if I have fixed the problem...

**Comment by archonwang** [comment]
urrr,,
it seems not solve the problem...
I tried to use command line to recompile assets.
`RAILS_ENV=production bundle exec rake assets:precompile`

but not effective...

**Comment by archonwang** [comment]
@Loriowar , Thanks. I found the plugin is ok, it caused by another plugin .

**Comment by Loriowar** [comment]
Is problem was in [charleneChen/redmine_issues_tree_view](https://github.com/charleneChen/redmine_issues_tree_view) or in an other plugin? If cause is other plugin, please, tell me a name of it. I want to add this one to Readme as an information for other users.

**Comment by archonwang** [comment]
@Loriowar , 
you are welcome, I have informed the author of plugin named contracts to fix the issue. and in the fork repo of FireMartZ has fixed the issue.
