### ISSUE TITLE
Does it works for Bitnami Redmine 3.0.3?

### ISSUE THREAD

**Issue by nickyxyy** [Loriowar/redmine_issues_tree#49]
I try to deploy the plug-in for Bitnami Redmine 3.0.3 but it doesn't work. Furthermore, the Redmine service can't be enabled after the installation? It is appreciated if you can help provide the installation guide in Bitnami Redmine.

I thank you in advance

**Comment by nickyxyy** [comment]
@Loriowar

**Comment by Loriowar** [comment]
I haven't an experience with Bitnami, but this plugin must work with any version of Redmine from 2.5 till 3.3. Moreover, from time to time I see a people, whom use this plugin on Bitnami, but I don't know any details about installation or about any other specific moments.

In future I can try to write an minimalistic guide about Bitnami, but I can't provide an estimate of this task. So, you can wait or try to install this by your self and provide me an pull request with description of process or at least you can provide a base information about work with Bitnami.

**Comment by Loriowar** [comment]
No response for a long time. Closed.
