### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by UruKpo** [Loriowar/redmine_issues_tree#52]
I am using Bitnami Redmine 3.1.1. I downloaded and copied redmine_issues_tree from branch 3.1.0 to my plugins directory. Next I ran bundle install and error ocurred:
"Command 'bundle install' failed with return code 17 and error message '"
![issue_tree_instalation_error](https://cloud.githubusercontent.com/assets/28738066/26120671/e083a6a8-3a47-11e7-9191-9b6a5f300052.jpg)

**Comment by Daiben** [comment]
Hey @UruKpo 
Check http://www.redmine.org/projects/redmine/wiki/Plugins for plugin installation.

Error code 17 looks more like a client error then that there is something wrong with this plugin / your server.

You could check the /var/log/ directory for more information in linux. 

And could you also provide more information? how to reproduce?

**Comment by Loriowar** [comment]
No responce for a long time. Closed.
