### ISSUE TITLE
Opened issues inside closed issues appear as "root"

### ISSUE THREAD

**Issue by rvcoutinho** [Loriowar/redmine_issues_tree#55]
When there is an opened issue whose parent is closed, this opened issue appears a "root" issue - which totally breaks issue organization. Ideally, the closed parent should also be present (maybe crossed out). 

This would be really good.

Would it be easy to implement?

**Comment by Loriowar** [comment]
This is a feature, not bug. Firstly issues filtered according to you query conditions. Secondly, issues organized in a tree. If root issue do not included in a result of query, you can see a children on a first level of hierarchy. As I know, many people use this behavior and I don't want to change this. So, you must use a query mechanism for obtain a desired result.
