### ISSUE TITLE
Orphaned children

### ISSUE THREAD

**Issue by meierzwo** [Loriowar/redmine_issues_tree#59]
Hi,

Nice plugin! But I have the following question:

We have a parent issue with some child issues.
If the issue list is filtered by Updated timestamp, the parent issue is not displayed, when the date filter does not match. In this case you will see the child issue as orphaned children.
Is it possible to display the parent issues as well (even when the filter does not match)

Thank you for any reply.

**Comment by Loriowar** [comment]
Hello. Look at #55. You ask the same. If in short: this is a feature, not a bug. Moreover, realization of this feature required strong patching of Redmine query mechanism. This is monstrous and very dangerous thing. Strongly preferable to leave it as is. Stability is a main aim.

However, you can suggest an pull request for this purpose and we discuss it.
