### ISSUE TITLE
incompatibility with redmine_xlsx_format_issue_exporter pluggin

### ISSUE THREAD

**Issue by juliansotoca** [Loriowar/redmine_issues_tree#6]
If I try to run redmine_issues_tree plugin with the xlsx exporter also installed I got a 500 when I click the "tree view" link. Here there are some logs:

apache log

redmine.localhost:80 10.0.2.2 - - [18/Sep/2015:12:03:53 +0000] "GET /projects/a-project-b/issues HTTP/1.1" 200 8795 "http://redmine.localhost:8080/projects/a-project-b/issues?sort=id" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"
redmine.localhost:80 10.0.2.2 - - [18/Sep/2015:12:04:08 +0000] "POST /projects/a-project-b/issues_trees/redirect_with_params HTTP/1.1" 200 1646 "http://redmine.localhost:8080/projects/a-project-b/issues" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"
redmine.localhost:80 10.0.2.2 - - [18/Sep/2015:12:04:08 +0000] "GET /projects/a-project-b/issues_trees/tree_index?c%5B%5D=category&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=ubted_on&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=a-project-b&set_filter=1 HTTP/1.1" 500 799 "http://redmine.localhost:8080/projects/a-project-b/issues" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

 

redmine log

Started POST "/projects/a-project-b/issues_trees/redirect_with_params" for 10.0.2.2 at 2015-09-18 12:04:51 +0000
Processing by IssuesTreesController#redirect_with_params as JSON
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "f"=>["status_id", ""], "op"=>{"status_id"=>"o"}, "c"=>["category", "tracker", "status", "priority", "subject", "assigned_to", "ubted_on"], "group_by"=>"", "project_id"=>"a-project-b"}
  Current user: user (id=5)
Completed 200 OK in 9ms (Views: 0.3ms | ActiveRecord: 1.6ms)
Started GET "/projects/a-project-b/issues_trees/tree_index?c%5B%5D=category&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=ubted_on&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=a-project-b&set_filter=1" for 10.0.2.2 at 2015-09-18 12:04:51 +0000
Processing by IssuesTreesController#tree_index as HTML
  Parameters: {"c"=>["category", "tracker", "status", "priority", "subject", "assigned_to", "ubted_on"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"a-project-b", "set_filter"=>"1"}
  Current user: user (id=5)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (1.2ms)
  Rendered queries/_filters.html.erb (8.9ms)
  Rendered queries/_columns.html.erb (1.6ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (10.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (2.9ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (4.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (4.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (3.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (3.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (10.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml (50.6ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_view_issues_index_bottom.erb (2.0ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml within layouts/base (69.7ms)
Completed 500 Internal Server Error in 145ms (ActiveRecord: 15.5ms)

ActionView::Template::Error (undefined method `>' for nil:NilClass):
    20:         <label><%= check_box_tag 'description', '1', @query.has_column?(:description) %> <%= l(:field_description) %></label>
    21:         <label><%= check_box_tag 'files', '1', false %> <%= l(:label_attachment_plural) %></label>
    22:       </p>
    23:       <% if @issue_count > Setting.issues_export_limit.to_i %>
    24:           <p class="icon icon-warning">
    25:             <%= l(:setting_issues_export_limit) %>: <%= Setting.issues_export_limit.to_i %>
    26:           </p>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'

**Comment by Loriowar** [comment]
For a first view, problem appear due to `view_issues_index_bottom` hook in `tree_index` template. Renaming of the hook must solve this error. I will fix it in closest future.

**Comment by Loriowar** [comment]
I fixed hook name in `tree_index` template in all supported versions of the plugin. This must solve your problem. Please, check it.

**Comment by juliansotoca** [comment]
seems that works perfect, Thank you.

**Comment by Loriowar** [comment]
Thanks for use of my plugin.
