### ISSUE TITLE
Compatibility with Redmine 3.4

### ISSUE THREAD

**Issue by Loriowar** [Loriowar/redmine_issues_tree#60]
- [x] Check proper works of plugin settings after sen and drop default isses view setting. Apply 94fcd80ac6bffdb3c1e51d4d12da7f3cf178cdaa if needed.
- [x] Check diff between `app/views/issues/index.html.erb` from Redmine and patched view from plugin. Apply changes if needed.
- [x] Actualize view `app/views/issues_tree/issues_index.html.haml` from plugin according to last changes in Redmine.
- [x] Create new branch `3.4.x` and releace a new version of plugin.
- [x] Test work of all features.

**Comment by Jiangshan00001** [comment]
+1

**Comment by kiggyy** [comment]
Have never met Ruby before, so I just looked for analogue usages and prepared the patch for 10-15 minutes. At least it allowed me to run the plugin on 3.4:
[rm-3.4.2.patch.zip](https://github.com/Loriowar/redmine_issues_tree/files/1258612/rm-3.4.2.patch.zip)

**Comment by pilgrimpush** [comment]
+1 

Hello @Loriowar and thanks for your great plugin!
We now trying to move our Redmine to the latest version but we want to know if it's compatible and if not will you plan to release a new version any time soon?

Thanks!

**Comment by Loriowar** [comment]
@pilgrimpush this task created for monitor a progress of a new version of the plugin which compatible with Redmine 3.4. For now, plugin incompatible with Redmine 3.4. I will check a checkboxes in a first message of this issue after complete each step of a migration for informing users. Honestly speaking, I can't provide exact estimate. Estimate varying from couple weeks to couple months. Actually, this task required 6-8 hours of a real work, but I haven't this time for now. So, be patient or make a pull request with described changes and I'll be glad to merge it.

**Comment by Tab10id** [comment]
We already did all this changes but our version is not fully compatable
with github master branch. If all be good I will complete our pull request
on next week.

**Comment by Loriowar** [comment]
Released new version (0.0.11) of the plugin with support Redmine 3.4.
