### ISSUE TITLE
无法将redmine_issues_tree-2.5.3安装到windows 2003 server

### ISSUE THREAD

**Issue by wangshengshun** [Loriowar/redmine_issues_tree#7]
redmine 2.5.2.stable 无法正常安装redmine_issues_tree-2.5.3到的我的服务器上，我的服务器操作系统是windows 2003 server ,我用的安装方式是“Bitnami Redmine”方式进行安装，安装的时候出现错误：
[31mCould not find gem 'require_patch (~> 0.1.0) x86-mingw32' in the gems avail
able on this machine.[0m
[33mRun `bundle install` to install missing gems.[0m
thank you !

**Comment by Loriowar** [comment]
Problem, related with operation system and installation of gems is not a problem of plugin. Plugin works correct if you resolve all required dependencies. You may contact with gem developer and talk about compatibility with non-Unix systems.
