### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by eng5** [Loriowar/redmine_issues_tree#73]
Hello,when I have installed this plugin,the following error occurred.
Is this a problem with my enviroment?

[error.txt](https://github.com/Loriowar/redmine_issues_tree/files/1882782/error.txt)

My enviroment
OS:CentOS7
redmine:bitnami redmine 3.4.4-3

**Comment by Loriowar** [comment]
As you can see, there is a problem with installation of `mysql2` gem. Most probably you forgot to install some dependency libs for it. Use google and stackoverflow for solve this issue (for example, [look at it](https://stackoverflow.com/questions/3608287/error-installing-mysql2-failed-to-build-gem-native-extension)). Current plugin doesn't involved in your problem.
