### ISSUE TITLE
bad version number

### ISSUE THREAD

**Issue by kileurf** [Loriowar/redmine_issues_tree#75]
Hello,

i've just install the new verison of the redmin_issues_tree ( normally 0.0.11 ) but on the redmine plugins panel, I always see the 0.0.10 verison.

And i saw in "redmine_issues_tree/lib/redmine_issues_tree/version.rb" the version is always 0.0.10.

Is it normal ?

Regrads,
Alexis

**Comment by Loriowar** [comment]
Please, read carefully ReadMe file. You install plugin from `master` branch. This is wrong way. Use branch with name corresponding to your Redmine version and all will be fine.

**Comment by adrianovieira** [comment]
What if you use tag numbering method instead of a branch?

**Comment by Loriowar** [comment]
@adrianovieira no way. If you look at source code of the plugin, you can find a major changes.  Same changes you can find in different Redime versions. Moreover, in case of tags you can't easily make a bugfix or an improvement. Anyway, you can try to do it locally to understand the problem deeply.
