### ISSUE TITLE
Internal error 500 happened on /my/account and /setting page

### ISSUE THREAD

**Issue by normansu-tw** [Loriowar/redmine_issues_tree#78]
Here is my error message in log file.

> Started GET "/my/account" for 127.0.0.1 at 2018-05-11 09:16:20 +0000
> Processing by MyController#account as HTML
> Current user: admin (id=1)
> Rendered my/account.html.erb within layouts/base (551.0ms)
> Completed 500 Internal Server Error in 563ms (ActiveRecord: 2.5ms)
> 
> ActionView::Template::Error (can not load translations from /home/redmine/redmine/plugins/redmine_issues_tree/config/locales/pt-BR.yml: #<Psych::SyntaxError: (/home/redmine/redmine/plugins/redmine_issues_tree/config/locales/pt-BR.yml): did not find expected key while parsing a block mapping at line 10 column 7>):
> 22:
> 
> <%= f.text_field :lastname, :required => true %>
> 
> 
> 23:
> <%= f.text_field :mail, :required => true %>
> 
> 
> 24: <% unless @user.force_default_language? %>
> 25:
> <%= f.select :language, lang_options_for_select %>
> 
> 
> 26: <% end %>
> 27: <% if Setting.openid? %>
> 28:
> <%= f.text_field :identity_url %>
> 
> 
> lib/redmine/i18n.rb:185:in init_translations' lib/redmine/i18n.rb:199:inlookup'
> lib/redmine/i18n.rb:121:in block in languages_options' lib/redmine/i18n.rb:121:inselect'
> lib/redmine/i18n.rb:121:in languages_options' lib/redmine/i18n.rb:126:inblock in languages_options'
> lib/redmine/i18n.rb:125:in languages_options' app/helpers/application_helper.rb:1180:inlang_options_for_select'
> app/views/my/account.html.erb:25:in block in _app_views_my_account_html_erb___51763069495662415_85841600' app/helpers/application_helper.rb:1190:inlabelled_form_for'
> app/views/my/account.html.erb:14:in _app_views_my_account_html_erb___51763069495662415_85841600' lib/redmine/sudo_mode.rb:63:insudo_mode'

**Comment by Loriowar** [comment]
Please, specify a name of a source branch of your locally installed plugin and a hash of a last commit in it.

**Comment by Loriowar** [comment]
Most likely you use old version of the plugin. This error fixed in commit 2c4f05b2c63a2355c05328ea6482234396056510. So, please, update plugin to last version and everything will be ok.
