### ISSUE TITLE
redmine_issues_tree not working

### ISSUE THREAD

**Issue by Senter000** [Loriowar/redmine_issues_tree#84]
Hi!

I am new to Redmine. 

I am using Redmine 3.4.6 on Windows 10

I installed redmine_issues_tree:
1. I downloaded the branch 3.4.x as zip file
2. I unzip the branch to D:\redmine-3.4.6\plugins\redmine_issues_tree-3.4.x
3. I called "bundle install"
4. I restarted Redmine
5. In Redmine I can see under Adminstration / Plugins the Redmine Issues Tree plugin

However there is no sign of the tree in the issues list. There is no expand and collapse button. There is no tree functionality.

Furthermore the Configure link in Adminstration / Plugins / Redmine Issues Tree plugin is not working (error 404: The page you were trying to access doesn't exist or has been removed.) 

Since I am new to Redmine I certainly missed something or made a mistake. It would be nice if somebody could guide me in the right direction.

Thanks.

**Comment by Loriowar** [comment]
Try to remove `-3.4.x` from directory name `plugins\redmine_issues_tree-3.4.x`. It must look like `D:\redmine-3.4.6\plugins\redmine_issues_tree`. Then repeat 3 and 4 steps.

**Comment by Senter000** [comment]
Great! This worked! Thank you very much for your help and Redmine Issues Tree.

**Comment by Loriowar** [comment]
Good luck!
