### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by rbartczak** [Loriowar/redmine_issues_tree#91]
Internal error 500 After click on Tree Icon.

Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [i386-mingw32]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  computed_custom_field          1.0.7
  redmine_auto_assign_group      0.1.1
  redmine_issues_tree            0.0.13
  redmine_questions              1.0.1
  redmineup_tags                 2.0.4

Log:

Processing by IssuesTreesController#redirect_with_params as JSON
  Parameters: {"utf8"=>"✓", "set_filter"=>"1", "sort"=>"id:desc", "f"=>["status_id", "tracker_id", ""], "op"=>{"status_id"=>"o", "tracker_id"=>"="}, "v"=>{"tracker_id"=>["4"]}, "c"=>["tracker", "status", "priority", "subject", "assigned_to", "updated_on", "cf_33"], "group_by"=>"", "t"=>[""], "project_id"=>"wydruki"}
  Current user: rafal.bartczak (id=5)
Completed 200 OK in 9ms (Views: 0.2ms | ActiveRecord: 2.8ms)
Started GET "/projects/wydruki/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&c%5B%5D=cf_33&f%5B%5D=status_id&f%5B%5D=tracker_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&op%5Btracker_id%5D=%3D&project_id=wydruki&set_filter=1&sort=id%3Adesc&t%5B%5D=&v%5Btracker_id%5D%5B%5D=4" for 127.0.0.1 at 2019-03-12 11:03:57 +0100
Processing by IssuesTreesController#tree_index as HTML
  Parameters: {"c"=>["tracker", "status", "priority", "subject", "assigned_to", "updated_on", "cf_33"], "f"=>["status_id", "tracker_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o", "tracker_id"=>"="}, "project_id"=>"wydruki", "set_filter"=>"1", "sort"=>"id:desc", "t"=>[""], "v"=>{"tracker_id"=>["4"]}}
  Current user: rafal.bartczak (id=5)
  Rendering plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb within layouts/base
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (6.7ms)
  Rendered queries/_filters.html.erb (133.3ms)
  Rendered queries/_columns.html.erb (2.9ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_query_form.html.erb (452.0ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb (48.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb (2.6ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.erb (2.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.erb (141.6ms)
  Rendered plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb (385.4ms)
  Rendered issues/_sidebar.html.erb (416.8ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb within layouts/base (1445.5ms)
Completed 500 Internal Server Error in 2279ms (ActiveRecord: 408.9ms)
  
ActionView::Template::Error (undefined local variable or method `sidebar_tags' for #<#<Class:0x08b84350>:0x08b7f088>
Did you mean?  sidebar_queries):
    1: <% unless sidebar_tags.empty? -%>
    2: <div class="sidebar-tags">
    3:   <h3><%= l(:tags) %></h3>
    4:   <%= render_sidebar_tags %>
  
plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_plugins_redmineup_tags_app_views_issues__tags_sidebar_html_erb__996218469_71568084'
lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:57:in `map'
lib/redmine/hook/view_listener.rb:57:in `block in render_on'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/issues/_sidebar.html.erb:15:in `_app_views_issues__sidebar_html_erb__419054874_71589780'
plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:48:in `block in _plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb___835826764_73147680'
plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.erb:47:in `_plugins_redmine_issues_tree_app_views_issues_trees_tree_index_html_erb___835826764_73147680'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Can you help me ?

**Comment by racic** [comment]
I'm having the same issue with the environment as below. I'm also using the PurpleMine2 theme.

> Environment:
>   Redmine version                4.0.2.stable
>   Ruby version                   2.6.1-p33 (2019-01-30) [x86_64-linux]
>   Rails version                  5.2.2
>   Environment                    production
>   Database adapter               PostgreSQL
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Subversion                     1.9.5
>   Mercurial                      4.0
>   Bazaar                         2.8.0
>   Git                            2.11.0
>   Filesystem                     
> Redmine plugins:
>   redmine_checklists             3.1.14
>   redmine_issues_tree            0.0.13
>   redmineup_tags                 2.0.4

**Comment by Loriowar** [comment]
Hmm, looks like this issue is similar to incompatibility with `redmine_tags` plugin. Most likely, you must select between `redmineup_tags` and `redmine_issues_tree`. Because for now it doesn't work properly together. I'll try to fix it in the future, but no any eta for now.

**Comment by blavka** [comment]
Quick fix:

plugins/redmineup_tags/app/views/issues/_tags_sidebar.html.erb
```diff
--- a/_tags_sidebar.html.erb
+++ b/_tags_sidebar.html.erb.orig
@@ -1,8 +1,6 @@
-<% if defined?(sidebar_tags) && !sidebar_tags.empty? %>
 <% unless sidebar_tags.empty? -%>
 <div class="sidebar-tags">
   <h3><%= l(:tags) %></h3>
   <%= render_sidebar_tags %>
 </div>
 <% end -%>
-<% end %> 
```

**Comment by phuicy** [comment]
@blavka Thanks, this works for me.

**Comment by Loriowar** [comment]
Main discussion and an alternative patch located in #68
