### ISSUE TITLE
Not working in my 3.4.6

### ISSUE THREAD

**Issue by sapeyes** [Loriowar/redmine_issues_tree#92]
I've installed like below

/redmine/plugin$ git clone https://github.com/Loriowar/redmine_issues_tree.git
/redmine/plugin$ cd redmine_issues_tree
/redmine/plugin/redmine_issues_tree$ git checkout 3.4.x
/redmine/plugin/redmine_issues_tree$ bundle install
/redmine/plugin/redmine_issues_tree$ cd ../../
/redmine $ bundle install
/redmine $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
/redmine $ service apache2 restart

But my redmine goes wrong. 
![image](https://user-images.githubusercontent.com/960277/56190130-8f60e980-6064-11e9-93f1-2ceb54e02cfd.png)

My plugins 
* clipboard_image_paste  
* readme_at_repositories  
* redmine_bootstrap_kit  
* redmine_code_review  
* redmine_git_hosting  
* redmine_issue_badge  
* redmine_issue_checklist  
* redmine_landing_page  
* redmine_lightbox2  
* redmine_monitoring_controlling

**Comment by Loriowar** [comment]
Have you a traceback of the error in the log file?

**Comment by Loriowar** [comment]
Unable to reproduce. For me all works as expected with latest `3.4-stable` branch of Redmine.

**Comment by sapeyes** [comment]
It is working well now from last two weeks ago. 

I reinstalled rvm and ruby in local user environment. 
Otherwise, your update might make this effect. Thanks.
