### ISSUE TITLE
Unusable at Bitnami Redmine4.0.3

### ISSUE THREAD

**Issue by a845072422** [Loriowar/redmine_issues_tree#95]
D:\redmine\apps\redmine\htdocs\plugins>bundle exec rake redmine:plugins:migrate
RAILS_ENV=production NAME=redmine_issue_tree
(in D:/redmine/apps/redmine/htdocs)
rake aborted!
NoMethodError: undefined method `alias_method_chain' for IssuesController:Class
Did you mean?  alias_method
D:/redmine/apps/redmine/htdocs/plugins/redmine_issue_tree/lib/redmine_issues_tre
e/issues_controller_patch.rb:5:in `block in <module:IssuesControllerPatch>'
D:/redmine/apps/redmine/htdocs/plugins/redmine_issue_tree/init.rb:17:in `block i
n <top (required)>'
D:/redmine/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by a845072422** [comment]
@Loriowar How to solve this problem?

**Comment by Loriowar** [comment]
@a845072422 looks lile you use wrong version of the plugin. Most likely this is master. Instead of it you should use `4.0.x` branch of plugin according to your Redmine 4.0.3.

**Comment by a845072422** [comment]
@Loriowar I downloaded the latest version and it prompted compatibility with version redmin4.0.x

**Comment by a845072422** [comment]
@Loriowar It's really the reason for the plug-in version. Change it to another version.
