### ISSUE TITLE
Cannot run in 4.0.4 redmine.

### ISSUE THREAD

**Issue by xujohn** [Loriowar/redmine_issues_tree#96]
with redmine 4.0.4 stable encount following problem

undefined method `alias_method_chain' for IssuesController:Class
Did you mean?  alias_method (NoMethodError)
  /opt/redmine/plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:5:in `block in <module:IssuesControllerPatch>'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concern.rb:122:in `class_eval'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concern.rb:122:in `append_features'
  /var/lib/gems/2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:30:in `include'
  /var/lib/gems/2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:30:in `block in require_patch'
  /var/lib/gems/2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:23:in `each'
  /var/lib/gems/2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:23:in `require_patch'
  /opt/redmine/plugins/redmine_issues_tree/init.rb:17:in `block in <top (required)>'
  /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'

**Comment by Loriowar** [comment]
Looks like you use `master` branch. Please, take a look at ReadMe and use branch according to your Redmine version. In your case this is `4.0.*`. And all will be fine.
