### ISSUE TITLE
hide tags from ixti/redmine_tags

### ISSUE THREAD

**Issue by ilkosta** [Loriowar/redmine_issues_tree#97]
Hello, 
I'm trying to use the plugin but it hide the list of tags available using ixti/redmine_tags plugin
for reference see
https://github.com/ixti/redmine_tags/ and https://www.redmine.org/issues/1448 for the integration of this plugin inside the core.

**Comment by Loriowar** [comment]
As I remember, I added compatibility with `redmine_tags` a couple years ago in version `0.0.10`. Most likely there are some new changes and I should do this again. So, I'll implement it somewhere in the future.

**Comment by Loriowar** [comment]
Looks like you can use a patch from #68 for fix your issue. And anyway, `redmine_tags` is EOL. So, preferable to wait until implementing the same function in the core instead of support the old plugin.
