### ISSUE TITLE
The pager and "Also available in:~" below the issue list are lost

### ISSUE THREAD

**Issue by yakkung** [Loriowar/redmine_issues_tree#98]
If I switch to the tree view on the issue list screen, the pager and "Also available in:~" below the list will not be displayed.

**Comment by yakkung** [comment]
I didn't get a response to this issue, so I looked at the source code myself.
ruby can not understand at all, but found the following description in tree_index.html.erb.

<% # No pagination for tree%>
<% # No export links (ATOM, csv, etc) for tree%>

I consider this a specification.
Thank you very much.

※Sorry for my weird English.

**Comment by Tab10id** [comment]
@yakkung You can't paginate tree pretty well. If you see not a full tree there no simple way to understand that some tree nodes have subnodes on next page. This is why this plugin not try to do this and always show full three.
